// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1607086252);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1607086372);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 638);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "IN");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"5e35df69-949f-481d-856e-363caf20d709\",\"default-theme@mozilla.org\":\"5566f8e3-7d20-4379-aceb-f48955502cc8\",\"google@search.mozilla.org\":\"f4e534f8-57b9-416c-a12f-534c16a95fa2\",\"amazondotcom@search.mozilla.org\":\"62336ff7-945f-428d-ae8d-ca1fbe9ed1fc\",\"bing@search.mozilla.org\":\"40648b0c-0214-4b88-a954-287424f821f6\",\"ddg@search.mozilla.org\":\"9d2afe71-a1d9-41d8-bc4e-7793afd3a1a5\",\"twitter@search.mozilla.org\":\"231ac106-1819-4be4-8d8e-ec4377418c08\",\"wikipedia@search.mozilla.org\":\"478f55f5-546a-486a-9bcd-c78b95e1e719\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "a00e2d98-7a9e-467d-bc14-8f5d36f4759");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "ac801cde-1ee1-47d9-87af-ef89c743528e");
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1607086372);
user_pref("services.settings.main.hijack-blocklists.last_check", 1607086372);
user_pref("services.settings.main.language-dictionaries.last_check", 1607086372);
user_pref("services.settings.main.sites-classification.last_check", 1607086372);
user_pref("services.settings.security.onecrl.checked", 1607086372);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "2d067929-fafc-4ce0-872f-04548599caf7");
user_pref("toolkit.telemetry.prompted", 2);
